# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(blank=True, decimal_places=3, help_text='In Celcius', max_digits=6, null=True, verbose_name='Average temperature')),
                ('uncertainty', models.DecimalField(blank=True, decimal_places=3, help_text='The 95% confidence interval around the average', max_digits=6, null=True, verbose_name='Average temperature uncertainty')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature.Country')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('date', 'country')]),
        ),
    ]
